import { useEffect, useRef, useState } from "react";
import { parseVoiceIntent, type VoiceIntent } from "./voiceIntent";
import "./VoiceCommandPanel.css";

type SpeechRecognitionEventLike = { results: ArrayLike<{ 0: { transcript: string } }> };
type SpeechRecognitionLike = { lang: string; interimResults: boolean; continuous: boolean; start(): void; stop(): void; onresult?: (event: SpeechRecognitionEventLike) => void; onerror?: () => void; onend?: () => void };
type SpeechRecognitionConstructor = new () => SpeechRecognitionLike;

export function VoiceCommandPanel({ disabled, execute }: { disabled?: boolean; execute: (intent: Exclude<VoiceIntent, { kind: "unknown" }>) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [listening, setListening] = useState(false); const [text, setText] = useState(""); const [pending, setPending] = useState<VoiceIntent>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const recognition = useRef<SpeechRecognitionLike | undefined>(undefined);
  const SpeechRecognition = (window as unknown as { SpeechRecognition?: SpeechRecognitionConstructor; webkitSpeechRecognition?: SpeechRecognitionConstructor }).SpeechRecognition ?? (window as unknown as { webkitSpeechRecognition?: SpeechRecognitionConstructor }).webkitSpeechRecognition;
  useEffect(() => () => recognition.current?.stop(), []);
  const interpret = (value = text) => { const intent = parseVoiceIntent(value); setError(undefined); setPending(intent); return intent; };
  const run = async (intent: VoiceIntent) => { if (intent.kind === "unknown") return; setBusy(true); setError(undefined); try { await execute(intent); setText(""); setPending(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "Voice command failed."); } finally { setBusy(false); } };
  const listen = () => { if (!SpeechRecognition || listening) return; const instance = new SpeechRecognition(); recognition.current = instance; instance.lang = navigator.language || "en-US"; instance.interimResults = false; instance.continuous = false; instance.onresult = event => { const transcript = event.results[0]?.[0]?.transcript ?? ""; setText(transcript); setPending(parseVoiceIntent(transcript)); }; instance.onerror = () => setListening(false); instance.onend = () => setListening(false); setListening(true); instance.start(); };
  return <div className="voice-command"><button className={open ? "active" : ""} onClick={() => setOpen(value => !value)} title="Voice coding commands">◉ Voice</button>{open && <section><header><div><strong>Voice coding</strong><small>{SpeechRecognition ? "Speech recognition available" : "Speech API unavailable — type a command"}</small></div><button onClick={() => setOpen(false)}>×</button></header><div className="voice-input"><input value={text} onChange={event => { setText(event.target.value); setPending(undefined); setError(undefined); }} onKeyDown={event => event.key === "Enter" && interpret()} placeholder='Try “Open AuthService.cs”' /><button disabled={!SpeechRecognition || listening} onClick={listen}>{listening ? "Listening…" : "🎙"}</button><button disabled={!text.trim()} onClick={() => interpret()}>Preview</button></div>{pending && <article className={pending.kind === "unknown" ? "unknown" : ""}><small>{pending.risky ? "CONFIRMATION REQUIRED" : "COMMAND PREVIEW"}</small><p>{pending.summary}</p>{pending.kind === "unknown" ? <span>Supported: open file, explain, run tests, create a named branch, fix this error.</span> : <button disabled={busy || disabled && (pending.kind === "runTests" || pending.kind === "createBranch")} onClick={() => void run(pending)}>{busy ? "Working…" : pending.risky ? "Confirm and run" : "Run command"}</button>}</article>}{error && <p className="voice-error" role="alert">{error}</p>}<footer>Voice never applies AI code automatically. Execution and repository mutations always require confirmation.</footer></section>}</div>;
}
