import { useLanguage } from "./useLanguage";
import type { Language } from "../contexts/LanguageContext";

type Texts = Record<string, Record<Language, string>>;
const x = (en:string, az:string, ru:string, de:string, tr:string) => ({ en, az, ru, de, tr });

const texts: Texts = {
  unlockInsights:x("Unlock more insights","Daha çox analitika əldə edin","Откройте больше аналитики","Mehr Einblicke erhalten","Daha fazla analiz elde edin"), upgradeWorkspace:x("Upgrade your workspace to access advanced analytics.","Təkmil analitikaya giriş üçün iş sahənizi yeniləyin.","Обновите рабочее пространство для расширенной аналитики.","Aktualisieren Sie Ihren Arbeitsbereich für erweiterte Analysen.","Gelişmiş analizlere erişmek için çalışma alanınızı yükseltin."), viewPlans:x("View plans","Planlara bax","Посмотреть тарифы","Tarife anzeigen","Planları görüntüle"),
  login:x("Login","Giriş","Вход","Anmeldung","Giriş"), logout:x("Logout","Çıxış","Выход","Abmeldung","Çıkış"), logoutTitle:x("Sign out of your account","Hesabdan çıxın","Выйти из аккаунта","Vom Konto abmelden","Hesaptan çıkış yap"), logoutCopy:x("End this session securely. You will need to sign in again to access your workspace.","Bu sessiyanı təhlükəsiz bitirin. İş sahəsinə giriş üçün yenidən daxil olmalısınız.","Безопасно завершите этот сеанс. Для доступа к рабочему пространству потребуется повторный вход.","Beenden Sie diese Sitzung sicher. Für den Arbeitsbereich müssen Sie sich erneut anmelden.","Bu oturumu güvenle sonlandırın. Çalışma alanına erişmek için tekrar giriş yapmanız gerekir."), accountMenu:x("Account menu","Hesab menyusu","Меню аккаунта","Kontomenü","Hesap menüsü"), signedIn:x("User signed in.","İstifadəçi daxil oldu.","Пользователь вошёл в систему.","Benutzer hat sich angemeldet.","Kullanıcı oturum açtı."), signedOut:x("User signed out.","İstifadəçi çıxış etdi.","Пользователь вышел из системы.","Benutzer hat sich abgemeldet.","Kullanıcı oturumu kapattı."), system:x("System","Sistem","Система","System","Sistem"),
  totalUsers:x("Total users","Ümumi istifadəçilər","Всего пользователей","Benutzer gesamt","Toplam kullanıcı"), activeUsers30Days:x("Active users · 30 days","Aktiv istifadəçilər · 30 gün","Активные пользователи · 30 дней","Aktive Benutzer · 30 Tage","Aktif kullanıcılar · 30 gün"), suspendedUsers:x("Suspended users","Bloklanmış istifadəçilər","Приостановленные пользователи","Gesperrte Benutzer","Askıya alınan kullanıcılar"), totalProjects:x("Total projects","Ümumi layihələr","Всего проектов","Projekte gesamt","Toplam proje"), projects30Days:x("Projects · 30 days","Layihələr · 30 gün","Проекты · 30 дней","Projekte · 30 Tage","Projeler · 30 gün"), activity30Days:x("Activity · 30 days","Fəaliyyət · 30 gün","Активность · 30 дней","Aktivität · 30 Tage","Etkinlik · 30 gün"),
  projects:x("Projects","Layihələr","Проекты","Projekte","Projeler"),
  loadingAnalytics:x("Calculating workspace analytics…","İş sahəsi analitikası hesablanır…","Аналитика рабочего пространства рассчитывается…","Arbeitsbereich-Analysen werden berechnet…","Çalışma alanı analizleri hesaplanıyor…"),
  morning:x("Good morning","Sabahınız xeyir","Доброе утро","Guten Morgen","Günaydın"), afternoon:x("Good afternoon","Günortanız xeyir","Добрый день","Guten Tag","İyi günler"), evening:x("Good evening","Axşamınız xeyir","Добрый вечер","Guten Abend","İyi akşamlar"),
  dashboardCopy:x("Live analytics from the projects and teams you can access.","Giriş imkanınız olan layihə və komandaların canlı analitikası.","Актуальная аналитика доступных проектов и команд.","Live-Analysen Ihrer Projekte und Teams.","Erişebildiğiniz proje ve ekiplerin canlı analizleri."),
  viewReport:x("View report","Hesabata bax","Открыть отчёт","Bericht anzeigen","Raporu görüntüle"), weeklyProgress:x("Weekly progress","Həftəlik irəliləyiş","Недельный прогресс","Wöchentlicher Fortschritt","Haftalık ilerleme"),
  weeklyCopy:x("Recorded workspace events over the past 7 days","Son 7 gündə qeydə alınmış hadisələr","События за последние 7 дней","Ereignisse der letzten 7 Tage","Son 7 gündeki çalışma alanı etkinlikleri"),
  live:x("LIVE","CANLI","В ЭФИРЕ","LIVE","CANLI"), recentActivity:x("Recent activity","Son fəaliyyət","Последняя активность","Letzte Aktivitäten","Son etkinlikler"),
  recentCopy:x("Latest updates across your projects","Layihələrinizdəki son yeniliklər","Последние изменения в проектах","Neueste Projektaktualisierungen","Projelerinizdeki son güncellemeler"),
  viewAll:x("View all","Hamısına bax","Показать все","Alle anzeigen","Tümünü gör"), noActivity:x("No project activity has been recorded yet.","Hələ layihə fəaliyyəti qeydə alınmayıb.","Активность проектов ещё не зарегистрирована.","Noch keine Projektaktivität erfasst.","Henüz proje etkinliği kaydedilmedi."),
  continue:x("Continue where you left off","Qaldığınız yerdən davam edin","Продолжите с того места, где остановились","Dort weitermachen, wo Sie aufgehört haben","Kaldığınız yerden devam edin"),
  viewAllProjects:x("View all projects","Bütün layihələrə bax","Все проекты","Alle Projekte","Tüm projeleri gör"), noProjects:x("No projects yet","Hələ layihə yoxdur","Проектов пока нет","Noch keine Projekte","Henüz proje yok"),
  dashboardNoProjectsCopy:x("Create a project to start collecting workspace analytics.","Analitika toplamaq üçün layihə yaradın.","Создайте проект для сбора аналитики.","Erstellen Sie ein Projekt, um Analysen zu sammeln.","Analiz toplamaya başlamak için bir proje oluşturun."), goProjects:x("Go to projects","Layihələrə keç","Перейти к проектам","Zu Projekten","Projelere git"),
  activeProjects:x("Active projects","Aktiv layihələr","Активные проекты","Aktive Projekte","Aktif projeler"), savesWeek:x("Saves this week","Bu həftə saxlamalar","Сохранения за неделю","Speicherungen diese Woche","Bu haftaki kayıtlar"), taskCompletion:x("Task completion","Tapşırıq tamamlanması","Выполнение задач","Aufgabenabschluss","Görev tamamlama"), teamMembers:x("Team members","Komanda üzvləri","Участники команды","Teammitglieder","Ekip üyeleri"),
  fromLastWeek:x("from last week","keçən həftədən","с прошлой недели","seit letzter Woche","geçen haftadan"), acrossProjects:x("across your projects","layihələriniz üzrə","во всех проектах","projektübergreifend","projeleriniz genelinde"),
  yourWorkspace:x("YOUR WORKSPACE","SİZİN İŞ SAHƏNİZ","ВАШЕ РАБОЧЕЕ ПРОСТРАНСТВО","IHR ARBEITSBEREICH","ÇALIŞMA ALANINIZ"), projectsCopy:x("Create, organize, and collaborate with your team.","Komandanızla yaradın, təşkil edin və əməkdaşlıq edin.","Создавайте, организуйте и работайте вместе с командой.","Erstellen, organisieren und arbeiten Sie mit Ihrem Team zusammen.","Ekibinizle oluşturun, düzenleyin ve birlikte çalışın."),
  loadingProjects:x("Loading projects…","Layihələr yüklənir…","Проекты загружаются…","Projekte werden geladen…","Projeler yükleniyor…"), firstProject:x("Create your first project to start collaborating.","Əməkdaşlığa başlamaq üçün ilk layihənizi yaradın.","Создайте первый проект, чтобы начать совместную работу.","Erstellen Sie Ihr erstes Projekt für die Zusammenarbeit.","Birlikte çalışmaya başlamak için ilk projenizi oluşturun."), createProject:x("Create project","Layihə yarat","Создать проект","Projekt erstellen","Proje oluştur"),
  messages:x("MESSAGES","MESAJLAR","СООБЩЕНИЯ","NACHRICHTEN","MESAJLAR"), userIdDm:x("User ID for direct message","Şəxsi mesaj üçün istifadəçi ID-si","ID пользователя для личного сообщения","Benutzer-ID für Direktnachricht","Doğrudan mesaj için kullanıcı kimliği"), noConversations:x("No conversations yet.","Hələ söhbət yoxdur.","Диалогов пока нет.","Noch keine Unterhaltungen.","Henüz konuşma yok."),
  projectChannel:x("Project workspace channel","Layihə iş sahəsi kanalı","Канал проекта","Projektkanal","Proje çalışma alanı kanalı"), directConversation:x("Direct conversation","Şəxsi söhbət","Личный диалог","Direktunterhaltung","Doğrudan konuşma"), olderMessages:x("Load older messages","Köhnə mesajları yüklə","Загрузить старые сообщения","Ältere Nachrichten laden","Eski mesajları yükle"), read:x("Read","Oxundu","Прочитано","Gelesen","Okundu"), sent:x("Sent","Göndərildi","Отправлено","Gesendet","Gönderildi"), send:x("Send","Göndər","Отправить","Senden","Gönder"), selectConversation:x("Select a conversation","Söhbət seçin","Выберите диалог","Unterhaltung auswählen","Bir konuşma seçin"), conversationCopy:x("Your project channels and direct messages appear here.","Layihə kanalları və şəxsi mesajlar burada görünür.","Здесь появятся каналы проектов и личные сообщения.","Projektkanäle und Direktnachrichten erscheinen hier.","Proje kanallarınız ve doğrudan mesajlarınız burada görünür."), noMessages:x("No messages yet","Hələ mesaj yoxdur","Сообщений пока нет","Noch keine Nachrichten","Henüz mesaj yok"),
  typingOne:x("person is typing…","nəfər yazır…","пользователь печатает…","Person schreibt…","kişi yazıyor…"), typingMany:x("people are typing…","nəfər yazır…","пользователей печатают…","Personen schreiben…","kişi yazıyor…"),
  notifications:x("Notifications","Bildirişlər","Уведомления","Benachrichtigungen","Bildirimler"), inbox:x("INBOX","GƏLƏNLƏR","ВХОДЯЩИЕ","POSTEINGANG","GELEN KUTUSU"), notificationCenterCopy:x("Project activity, mentions, and direct messages in one place.","Layihə fəaliyyəti, qeydlər və şəxsi mesajlar bir yerdə.","События проектов, упоминания и личные сообщения в одном месте.","Projektaktivitäten, Erwähnungen und Direktnachrichten an einem Ort.","Proje etkinlikleri, bahsetmeler ve doğrudan mesajlar tek yerde."), markAllRead:x("Mark all as read","Hamısını oxunmuş et","Отметить все прочитанными","Alle als gelesen markieren","Tümünü okundu işaretle"), markRead:x("Mark as read","Oxunmuş et","Отметить прочитанным","Als gelesen markieren","Okundu işaretle"), allCaughtUp:x("You're all caught up","Bütün bildirişlərə baxmısınız","Все уведомления просмотрены","Alles ist auf dem neuesten Stand","Tüm bildirimleri gördünüz"), noNotifications:x("No notifications yet","Hələ bildiriş yoxdur","Уведомлений пока нет","Noch keine Benachrichtigungen","Henüz bildirim yok"), notificationEmptyCopy:x("New project activity, mentions, and messages will appear here.","Yeni layihə fəaliyyəti, qeydlər və mesajlar burada görünəcək.","Здесь появятся события проектов, упоминания и сообщения.","Neue Projektaktivitäten, Erwähnungen und Nachrichten erscheinen hier.","Yeni proje etkinlikleri, bahsetmeler ve mesajlar burada görünür."), viewNotificationCenter:x("View notification center","Bildiriş mərkəzinə bax","Открыть центр уведомлений","Benachrichtigungscenter öffnen","Bildirim merkezini görüntüle"), loadOlder:x("Load older notifications","Köhnə bildirişləri yüklə","Загрузить старые уведомления","Ältere Benachrichtigungen laden","Eski bildirimleri yükle"), loadingNotifications:x("Loading notifications…","Bildirişlər yüklənir…","Уведомления загружаются…","Benachrichtigungen werden geladen…","Bildirimler yükleniyor…"),
  platformControl:x("PLATFORM CONTROL","PLATFORMAYA NƏZARƏT","УПРАВЛЕНИЕ ПЛАТФОРМОЙ","PLATTFORMVERWALTUNG","PLATFORM KONTROLÜ"), administration:x("Administration","İdarəetmə","Администрирование","Administration","Yönetim"), adminCopy:x("Manage users, roles, projects, and the platform.","İstifadəçiləri, rolları, layihələri və platformanı idarə edin.","Управляйте пользователями, ролями, проектами и платформой.","Benutzer, Rollen, Projekte und Plattform verwalten.","Kullanıcıları, rolleri, projeleri ve platformu yönetin."), openAudit:x("Open audit log","Audit jurnalını aç","Открыть журнал аудита","Auditprotokoll öffnen","Denetim günlüğünü aç"),
  users:x("Users","İstifadəçilər","Пользователи","Benutzer","Kullanıcılar"), roles:x("Roles","Rollar","Роли","Rollen","Roller"), status:x("Status","Status","Статус","Status","Durum"), lastActive:x("Last active","Son aktivlik","Последняя активность","Zuletzt aktiv","Son etkinlik"), owner:x("Owner","Sahib","Владелец","Eigentümer","Sahip"), members:x("Members","Üzvlər","Участники","Mitglieder","Üyeler"), tasks:x("Tasks","Tapşırıqlar","Задачи","Aufgaben","Görevler"), public:x("Public","İctimai","Публичный","Öffentlich","Herkese açık"), private:x("Private","Şəxsi","Приватный","Privat","Özel"), active:x("Active","Aktiv","Активен","Aktiv","Aktif"), suspended:x("Suspended","Bloklanıb","Приостановлен","Gesperrt","Askıya alındı"), activate:x("Activate","Aktivləşdir","Активировать","Aktivieren","Etkinleştir"), suspend:x("Suspend","Blokla","Приостановить","Sperren","Askıya al"), delete:x("Delete","Sil","Удалить","Löschen","Sil"),
  previous:x("Previous","Əvvəlki","Назад","Zurück","Önceki"), next:x("Next","Növbəti","Далее","Weiter","Sonraki"), page:x("Page","Səhifə","Страница","Seite","Sayfa"), records:x("records","qeyd","записей","Einträge","kayıt"), loadingData:x("Loading data…","Məlumatlar yüklənir…","Данные загружаются…","Daten werden geladen…","Veriler yükleniyor…"),
  adminAudit:x("ADMIN AUDIT","ADMİN AUDİTİ","АУДИТ АДМИНИСТРАТОРА","ADMIN-AUDIT","YÖNETİCİ DENETİMİ"), activityLog:x("Activity log","Fəaliyyət jurnalı","Журнал активности","Aktivitätsprotokoll","Etkinlik günlüğü"), auditCopy:x("Review security and workspace events without exposing sensitive data.","Həssas məlumatları göstərmədən təhlükəsizlik və iş sahəsi hadisələrini nəzərdən keçirin.","Просматривайте события безопасности без раскрытия конфиденциальных данных.","Sicherheits- und Arbeitsbereichsereignisse ohne sensible Daten prüfen.","Hassas verileri açığa çıkarmadan güvenlik ve çalışma alanı olaylarını inceleyin."),
  userId:x("User ID","İstifadəçi ID-si","ID пользователя","Benutzer-ID","Kullanıcı kimliği"), projectId:x("Project ID","Layihə ID-si","ID проекта","Projekt-ID","Proje kimliği"), actionType:x("Action type","Əməliyyat növü","Тип действия","Aktionstyp","İşlem türü"), entityType:x("Entity type","Obyekt növü","Тип сущности","Entitätstyp","Varlık türü"), fromDate:x("From date","Başlanğıc tarixi","Дата начала","Von Datum","Başlangıç tarihi"), toDate:x("To date","Son tarix","Дата окончания","Bis Datum","Bitiş tarihi"),
  when:x("When","Tarix","Когда","Zeitpunkt","Zaman"), user:x("User","İstifadəçi","Пользователь","Benutzer","Kullanıcı"), project:x("Project","Layihə","Проект","Projekt","Proje"), actionLabel:x("Action","Əməliyyat","Действие","Aktion","İşlem"), entity:x("Entity","Obyekt","Сущность","Entität","Varlık"), description:x("Description","Təsvir","Описание","Beschreibung","Açıklama"), loadingActivity:x("Loading activity…","Fəaliyyət yüklənir…","Активность загружается…","Aktivitäten werden geladen…","Etkinlik yükleniyor…"), noMatching:x("No matching activity","Uyğun fəaliyyət yoxdur","Подходящих событий нет","Keine passenden Aktivitäten","Eşleşen etkinlik yok"), filtersCopy:x("Try changing the filters or date range.","Filtrləri və ya tarix aralığını dəyişin.","Измените фильтры или диапазон дат.","Ändern Sie Filter oder Datumsbereich.","Filtreleri veya tarih aralığını değiştirin."), fullUuidRequired:x("Enter the complete UUID shown in the user or project profile.","İstifadəçi və ya layihə profilində göstərilən tam UUID-ni daxil edin.","Введите полный UUID из профиля пользователя или проекта.","Geben Sie die vollständige UUID aus dem Benutzer- oder Projektprofil ein.","Kullanıcı veya proje profilinde gösterilen UUID'nin tamamını girin."), events:x("events","hadisə","событий","Ereignisse","etkinlik"),
};

export function usePageTranslation() {
  const { language } = useLanguage();
  return {
    language,
    pt: (key: keyof typeof texts) => texts[key][language],
    locale: ({en:"en-US",az:"az-AZ",ru:"ru-RU",de:"de-DE",tr:"tr-TR"} as const)[language],
  };
}

const weekdays:Record<Language,string[]>={en:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],az:["Bazar","Bazar ertəsi","Çərşənbə axşamı","Çərşənbə","Cümə axşamı","Cümə","Şənbə"],ru:["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"],de:["Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"],tr:["Pazar","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi"]};
const months:Record<Language,string[]>={en:["January","February","March","April","May","June","July","August","September","October","November","December"],az:["Yanvar","Fevral","Mart","Aprel","May","İyun","İyul","Avqust","Sentyabr","Oktyabr","Noyabr","Dekabr"],ru:["Января","Февраля","Марта","Апреля","Мая","Июня","Июля","Августа","Сентября","Октября","Ноября","Декабря"],de:["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"],tr:["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"]};
export function formatDashboardDate(date:Date,language:Language){const weekday=weekdays[language][date.getDay()],month=months[language][date.getMonth()],day=date.getDate();return language==="en"?`${weekday}, ${month} ${day}`:`${weekday}, ${day} ${month}`;}
