import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useToast } from "../../contexts/ToastContext";
import { useProject } from "../projects/hooks";
import { queryKeys } from "../../services/queryKeys";
import { databaseMetadataApi, type DatabaseMigration, type DatabaseProvider, type DatabaseTable, type MigrationColumn, type ProjectDatabase } from "./api";

const providers: Array<{ id: DatabaseProvider; name: string; detail: string; defaultSchema: string }> = [
  { id: "PostgreSQL", name: "PostgreSQL", detail: "UUID, jsonb and timezone-aware timestamps", defaultSchema: "public" },
  { id: "MySQL", name: "MySQL", detail: "CHAR UUIDs and datetime(6)", defaultSchema: "app" },
  { id: "SQLServer", name: "SQL Server", detail: "uniqueidentifier and datetimeoffset", defaultSchema: "dbo" },
  { id: "SQLite", name: "SQLite", detail: "Portable file database with dynamic typing", defaultSchema: "main" },
];

export function DatabaseExplorer({ projectId }: { projectId: string }) {
  const queryClient = useQueryClient();
  const { show } = useToast();
  const project = useProject(projectId);
  const query = useQuery({ queryKey: queryKeys.database(projectId), queryFn: () => databaseMetadataApi.schema(projectId), enabled: Boolean(projectId) });
  const [selectedName, setSelectedName] = useState<string>();
  const [provider, setProvider] = useState<DatabaseProvider>("PostgreSQL");
  const [schemaName, setSchemaName] = useState("public");
  const [migrationOpen, setMigrationOpen] = useState(false);
  const canConfigure = project.data?.currentUserRole === "Owner" || project.data?.currentUserRole === "Admin";
  const configure = useMutation({ mutationFn: () => databaseMetadataApi.configure(projectId, { provider, schemaName }), onSuccess: data => { queryClient.setQueryData<ProjectDatabase>(queryKeys.database(projectId), data); show(`${provider} workspace schema created.`); }, onError: error => show(error instanceof Error ? error.message : "Database configuration failed.", "error") });
  if (query.isLoading || project.isLoading) return <div className="nexa-loading" role="status">Loading workspace database…</div>;
  if (query.isError) return <section className="nexa-empty"><span>!</span><h2>Schema unavailable</h2><p>{query.error instanceof Error ? query.error.message : "The schema could not be loaded."}</p><button className="nexa-secondary-action" onClick={() => void query.refetch()}>Retry</button></section>;
  if (!query.data?.isConfigured) return <DatabaseSetup provider={provider} schemaName={schemaName} canConfigure={canConfigure} pending={configure.isPending} onProvider={next => { setProvider(next); setSchemaName(providers.find(item => item.id === next)!.defaultSchema); }} onSchemaName={setSchemaName} onSubmit={() => configure.mutate()} />;
  const tables = query.data.schemas.flatMap(schema => schema.tables);
  const selected = tables.find(table => `${table.schema}.${table.name}` === selectedName) ?? tables[0];
  return <><div className="database-connection-summary"><div><small>WORKSPACE DATABASE</small><strong>{query.data.provider}</strong><span>Schema v{query.data.version}</span></div><div className="database-summary-actions">{canConfigure && <button className="ui-button primary" onClick={() => setMigrationOpen(value => !value)}>+ Migration</button>}<code>{projectId.slice(0, 8)}</code></div></div>{migrationOpen && <MigrationWorkbench projectId={projectId} database={query.data} onClose={() => setMigrationOpen(false)} />}<div className="database-explorer"><aside><header><strong>SCHEMAS</strong><span>{tables.length} tables</span></header>{query.data.schemas.map(schema => <section key={schema.name}><h2>{schema.name}</h2>{schema.tables.map(table => <button className={table === selected ? "active" : ""} key={`${table.schema}.${table.name}`} onClick={() => setSelectedName(`${table.schema}.${table.name}`)}><span>▦</span>{table.name}<small>{table.columns.length}</small></button>)}</section>)}</aside><main>{selected && <TableDetails table={selected} />}</main><aside className="metadata-summary">{selected && <><header><strong>METADATA</strong></header><dl><div><dt>Provider</dt><dd>{query.data.provider}</dd></div><div><dt>Schema</dt><dd>{selected.schema}</dd></div><div><dt>Table</dt><dd>{selected.name}</dd></div><div><dt>Columns</dt><dd>{selected.columns.length}</dd></div><div><dt>Relationships</dt><dd>{selected.foreignKeys.length}</dd></div><div><dt>Indexes</dt><dd>{selected.indexes.length}</dd></div></dl><p>This schema belongs only to this workspace. Platform tables and credentials are never exposed.</p></>}</aside></div></>;
}

function MigrationWorkbench({ projectId, database, onClose }: { projectId: string; database: ProjectDatabase; onClose: () => void }) {
  const queryClient = useQueryClient(); const { show } = useToast();
  const history = useQuery({ queryKey: [...queryKeys.database(projectId), "migrations"], queryFn: () => databaseMetadataApi.migrations(projectId) });
  const [name, setName] = useState("add_table"); const [table, setTable] = useState(""); const [schema, setSchema] = useState(database.schemas[0]?.name ?? "public");
  const [columns, setColumns] = useState<MigrationColumn[]>([{ name: "id", type: "uuid", isNullable: false, isUnique: true }, { name: "name", type: "string", isNullable: false, isUnique: false }]);
  const create = useMutation({ mutationFn: () => databaseMetadataApi.createTableMigration(projectId, { name, schema, table, columns, expectedVersion: database.version }), onSuccess: data => { queryClient.setQueryData<DatabaseMigration[]>([...queryKeys.database(projectId), "migrations"], old => [data, ...(old ?? [])]); show("Migration draft created. Review the DDL before applying."); }, onError: error => show(error instanceof Error ? error.message : "Migration failed.", "error") });
  const apply = useMutation({ mutationFn: (id: string) => databaseMetadataApi.applyMigration(projectId, id, { expectedVersion: database.version, confirm: true }), onSuccess: data => { queryClient.setQueryData(queryKeys.database(projectId), data); void queryClient.invalidateQueries({ queryKey: [...queryKeys.database(projectId), "migrations"] }); show("Migration applied."); onClose(); }, onError: error => show(error instanceof Error ? error.message : "Apply failed.", "error") });
  const updateColumn = (index: number, patch: Partial<MigrationColumn>) => setColumns(items => items.map((item, i) => i === index ? { ...item, ...patch } : item));
  return <section className="migration-workbench"><header><div><small>SAFE SCHEMA MIGRATIONS</small><h2>Create table draft</h2><p>Preview first, then explicitly apply. Raw SQL is never executed against the platform database.</p></div><button className="icon-button" aria-label="Close migration workbench" onClick={onClose}>×</button></header><form onSubmit={event => { event.preventDefault(); create.mutate(); }}><label>Migration<input value={name} onChange={event => setName(event.target.value)} required pattern="[A-Za-z][A-Za-z0-9_]*" /></label><label>Schema<select value={schema} onChange={event => setSchema(event.target.value)}>{database.schemas.map(item => <option key={item.name}>{item.name}</option>)}</select></label><label>Table<input value={table} onChange={event => setTable(event.target.value)} required pattern="[A-Za-z][A-Za-z0-9_]*" placeholder="projects" /></label><div className="migration-columns"><strong>Columns</strong>{columns.map((column, index) => <div key={index}><input aria-label={`Column ${index + 1} name`} value={column.name} onChange={event => updateColumn(index, { name: event.target.value })} required pattern="[A-Za-z][A-Za-z0-9_]*"/><select aria-label={`Column ${index + 1} type`} value={column.type} onChange={event => updateColumn(index, { type: event.target.value as MigrationColumn["type"] })}>{["uuid","string","text","integer","boolean","decimal","timestamp"].map(type => <option key={type}>{type}</option>)}</select><label><input type="checkbox" checked={!column.isNullable} onChange={event => updateColumn(index, { isNullable: !event.target.checked })}/>Required</label><label><input type="checkbox" checked={column.isUnique} onChange={event => updateColumn(index, { isUnique: event.target.checked })}/>Unique</label><button type="button" aria-label={`Remove column ${index + 1}`} disabled={columns.length === 1} onClick={() => setColumns(items => items.filter((_, i) => i !== index))}>×</button></div>)}<button type="button" className="nexa-secondary-action" onClick={() => setColumns(items => [...items, { name: "", type: "string", isNullable: true, isUnique: false }])}>+ Column</button></div><button className="ui-button primary" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create preview"}</button></form><div className="migration-history"><h3>Migration history</h3>{history.isLoading && <p>Loading…</p>}{history.data?.map(item => <article key={item.id}><header><div><strong>{item.name}</strong><span className={`migration-status ${item.status.toLowerCase()}`}>{item.status}</span></div><small>Base schema v{item.baseVersion}</small></header><pre>{item.ddlPreview}</pre>{item.status === "Draft" && <button className="ui-button primary" disabled={apply.isPending} onClick={() => { if (window.confirm(`Apply ${item.name}? This updates the workspace schema blueprint.`)) apply.mutate(item.id); }}>Review complete — Apply</button>}</article>)}</div></section>;
}

function DatabaseSetup({ provider, schemaName, canConfigure, pending, onProvider, onSchemaName, onSubmit }: { provider: DatabaseProvider; schemaName: string; canConfigure: boolean; pending: boolean; onProvider: (value: DatabaseProvider) => void; onSchemaName: (value: string) => void; onSubmit: () => void }) {
  return <section className="database-setup"><header><span>DATABASE SETUP</span><h2>Choose this workspace’s database</h2><p>The selection is stored per project and generates a provider-specific starter schema. It does not expose or reuse the platform database.</p></header><div className="database-provider-grid">{providers.map(item => <button type="button" key={item.id} className={provider === item.id ? "active" : ""} onClick={() => onProvider(item.id)} disabled={!canConfigure}><strong>{item.name}</strong><small>{item.detail}</small></button>)}</div><form onSubmit={event => { event.preventDefault(); onSubmit(); }}><label>Schema or database namespace<input required pattern="[A-Za-z][A-Za-z0-9_]*" maxLength={63} value={schemaName} onChange={event => onSchemaName(event.target.value)} /></label>{canConfigure ? <button className="ui-button primary" disabled={pending || !schemaName.trim()}>{pending ? "Creating schema…" : `Create ${provider} schema`}</button> : <p>Only a project Owner or Admin can configure the workspace database.</p>}</form></section>;
}

function TableDetails({ table }: { table: DatabaseTable }) { return <><header className="table-detail-header"><div><span>TABLE</span><h2>{table.schema}.<strong>{table.name}</strong></h2></div></header><section className="schema-section"><h3>Columns</h3><div className="schema-table"><div className="schema-row heading"><span>Name</span><span>Type</span><span>Constraints</span><span>Nullable</span></div>{table.columns.map(column => <div className="schema-row" key={column.name}><code>{column.name}</code><code>{column.dataType}</code><span>{column.isPrimaryKey && <b>PK</b>}{column.isUnique && !column.isPrimaryKey && <b>UNIQUE</b>}{!column.isPrimaryKey && !column.isUnique && "—"}</span><span>{column.isNullable ? "YES" : "NO"}</span></div>)}</div></section><section className="schema-section split"><div><h3>Relationships</h3>{table.foreignKeys.length ? table.foreignKeys.map(key => <article className="metadata-item" key={key.name}><code>{key.sourceColumns.join(", ")}</code><span>→</span><code>{key.targetTable}.{key.targetColumns.join(", ")}</code></article>) : <p>No foreign keys.</p>}</div><div><h3>Indexes</h3>{table.indexes.length ? table.indexes.map(index => <article className="metadata-item" key={index.name}><code>{index.name}</code><span>{index.isUnique ? "UNIQUE" : "INDEX"}</span><small>{index.columns.join(", ")}</small></article>) : <p>No indexes.</p>}</div></section></>; }
