import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { graphKeys, knowledgeGraphApi, type GraphNode, type ImpactAnalysis, type ImpactItem } from "../features/knowledge-graph/api";
import { useToast } from "../contexts/ToastContext";

const colors:Record<string,string>={File:"#7299ff",Import:"#8990a3",Class:"#b67cff",Interface:"#d68cff",Method:"#77b8ff",Controller:"#ff8f70",Service:"#55d3ad",ApiEndpoint:"#ffbf69",DatabaseTable:"#f07dac",Component:"#61d5ec",Test:"#99d267"};
export function KnowledgeGraphPage(){
 const {projectId=""}=useParams();const client=useQueryClient();const {show}=useToast();const [selectedId,setSelectedId]=useState<string>();const [filter,setFilter]=useState("");
 const graph=useQuery({queryKey:graphKeys.graph(projectId),queryFn:()=>knowledgeGraphApi.get(projectId),retry:false});
 const impact=useQuery({queryKey:graphKeys.impact(projectId,selectedId??""),queryFn:()=>knowledgeGraphApi.impact(projectId,selectedId!),enabled:Boolean(selectedId)});
 const index=useMutation({mutationFn:()=>knowledgeGraphApi.index(projectId),onSuccess:value=>{client.setQueryData(graphKeys.graph(projectId),value);setSelectedId(undefined);show(`Indexed ${value.fileCount} files into graph v${value.version}.`)},onError:error=>show(error.message,"error")});
 const report=useMutation({mutationFn:()=>knowledgeGraphApi.report(projectId,selectedId!),onSuccess:value=>client.setQueryData(graphKeys.impact(projectId,selectedId!),value),onError:error=>show(error.message,"error")});
 const visible=useMemo(()=>{const value=graph.data;if(!value)return[];const q=filter.trim().toLowerCase();return value.nodes.filter(node=>!q||node.name.toLowerCase().includes(q)||node.path?.toLowerCase().includes(q)||node.kind.toLowerCase().includes(q)).slice(0,160)},[graph.data,filter]);
 return <main className="graph-page"><header className="graph-page-header"><div><span>CODE INTELLIGENCE</span><h1>Project Knowledge Graph</h1><p>Trace imports, symbols, APIs, tables, components and tests from persisted workspace evidence.</p></div><button className="ui-button primary" disabled={index.isPending} onClick={()=>index.mutate()}>{index.isPending?"Indexing…":graph.data?"Refresh graph":"Index project"}</button></header>
 {graph.isLoading?<div className="route-loader">Loading knowledge graph…</div>:graph.isError?<div className="graph-empty"><h2>No current graph</h2><p>Indexing is explicit and bounded. Binary files are never parsed.</p><button className="ui-button primary" onClick={()=>index.mutate()}>Create graph</button></div>:graph.data&&<><section className="graph-metrics"><article><b>{graph.data.fileCount}</b><span>Text files</span></article><article><b>{graph.data.totalNodes}</b><span>Nodes</span></article><article><b>{graph.data.totalEdges}</b><span>Relationships</span></article><article><b>v{graph.data.version}</b><span>{new Date(graph.data.indexedAt).toLocaleString()}</span></article></section><div className="graph-toolbar"><input value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Filter file, symbol or kind…"/><span>Showing {visible.length} interactive nodes{graph.data.isTruncated?" · API response bounded":""}</span></div><div className="graph-workbench"><GraphCanvas nodes={visible} edges={graph.data.edges} selectedId={selectedId} select={setSelectedId}/><ImpactPanel value={impact.data} loading={impact.isLoading} generating={report.isPending} generate={()=>report.mutate()}/></div></>}
 </main>;
}

function GraphCanvas({nodes,edges,selectedId,select}:{nodes:GraphNode[];edges:{fromNodeId:string;toNodeId:string;kind:string}[];selectedId?:string;select:(id:string)=>void}){
 const positions=useMemo(()=>{const byKind=new Map<string,GraphNode[]>();nodes.forEach(node=>byKind.set(node.kind,[...(byKind.get(node.kind)??[]),node]));const map=new Map<string,{x:number;y:number}>();[...byKind.entries()].forEach(([_,items],column)=>items.forEach((node,row)=>map.set(node.id,{x:40+column*210,y:45+row*86})));return map},[nodes]);const width=Math.max(900,new Set(nodes.map(x=>x.kind)).size*210+80);const height=Math.max(620,Math.max(0,...[...positions.values()].map(x=>x.y))+100);const ids=new Set(nodes.map(x=>x.id));
 return <div className="graph-canvas-wrap"><div className="graph-legend">{Object.entries(colors).map(([kind,color])=><span key={kind}><i style={{background:color}}/>{kind}</span>)}</div><svg className="graph-canvas" viewBox={`0 0 ${width} ${height}`} aria-label="Project dependency graph">{edges.filter(edge=>ids.has(edge.fromNodeId)&&ids.has(edge.toNodeId)).slice(0,1200).map(edge=>{const a=positions.get(edge.fromNodeId)!,b=positions.get(edge.toNodeId)!;return <line key={`${edge.fromNodeId}-${edge.toNodeId}-${edge.kind}`} x1={a.x+74} y1={a.y+25} x2={b.x+74} y2={b.y+25}/>})}{nodes.map(node=>{const p=positions.get(node.id)!;return <g key={node.id} transform={`translate(${p.x} ${p.y})`} className={selectedId===node.id?"selected":""} onClick={()=>select(node.id)} role="button"><rect width="150" height="52" rx="10" style={{stroke:colors[node.kind]}}/><text x="10" y="18" className="node-kind">{node.kind}</text><text x="10" y="38">{clip(node.name,21)}</text></g>})}</svg></div>;
}
function ImpactPanel({value,loading,generating,generate}:{value?:ImpactAnalysis;loading:boolean;generating:boolean;generate:()=>void}){if(loading)return <aside className="impact-panel"><div className="route-loader">Tracing impact…</div></aside>;if(!value)return <aside className="impact-panel empty"><h2>Select a node</h2><p>Inspect “who uses this?”, dependencies and potential breakage paths.</p></aside>;const groups:[string,ImpactItem[]][]=[["Affected files",value.affectedFiles],["Services / controllers",value.services],["API endpoints",value.apiEndpoints],["Tests",value.tests],["Database objects",value.databaseObjects],["Frontend components",value.frontendComponents],["What this depends on",value.dependencies],["Who uses this",value.usedBy]];return <aside className="impact-panel"><header><span>Potential impact</span><h2>{value.selectedName}</h2><button disabled={generating} onClick={generate}>{generating?"Asking Ollama…":"Generate Impact Report"}</button></header>{value.modelReport&&<div className="impact-report"><b>Ollama report</b><p>{value.modelReport}</p></div>}{!value.modelAvailable&&<small className="impact-model-state">Graph evidence is available. No model report has been generated.</small>}<div className="impact-groups">{groups.map(([label,items])=><details key={label} open={items.length>0&&items.length<8}><summary><b>{label}</b><span>{items.length}</span></summary>{items.length?items.slice(0,100).map(item=><article key={`${label}-${item.nodeId}`}><i style={{background:colors[item.kind]}}/><div><b>{item.name}</b><small>{item.path??item.kind} · distance {item.distance} · {Math.round(item.confidence*100)}%</small></div></article>):<p>No evidenced relationship.</p>}</details>)}</div></aside>}
const clip=(value:string,max:number)=>value.length<=max?value:`${value.slice(0,max-1)}…`;
