import { useEffect, useMemo, useState } from "react";
import { useToast } from "../contexts/ToastContext";
import { marketplaceApi } from "../features/marketplace/api";
import { filterSampleMarketplace } from "../features/marketplace/sampleData";
import type { CreateMarketplaceInput, MarketplaceCategory, MarketplaceItem } from "../features/marketplace/types";
import { useProjects } from "../features/projects/hooks";

const categories: Array<{ value: "" | MarketplaceCategory; label: string }> = [{ value: "", label: "All" }, { value: "ProjectTemplate", label: "Templates" }, { value: "Theme", label: "Themes" }, { value: "Plugin", label: "Plugins" }, { value: "AiAgent", label: "AI Agents" }, { value: "Snippet", label: "Snippets" }, { value: "Component", label: "Components" }];
const dangerous = new Set(["editor.write", "project.write", "network.request", "terminal.run"]);

export function MarketplacePage() {
  const [items, setItems] = useState<MarketplaceItem[]>([]); const [category, setCategory] = useState<"" | MarketplaceCategory>(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [publishOpen, setPublishOpen] = useState(false);
  const projects = useProjects(); const { show } = useToast();
  const load = async () => { setLoading(true); try { const result = await marketplaceApi.list(category || undefined, search || undefined); setItems(result.length ? result : filterSampleMarketplace(category || undefined, search || undefined)); } catch (error) { show(error instanceof Error ? error.message : "Marketplace could not load.", "error"); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 200); return () => window.clearTimeout(timer); }, [category, search]);
  const update = (next: MarketplaceItem) => setItems(current => current.map(item => item.id === next.id ? next : item));
  const install = async (item: MarketplaceItem) => { const projectId = projects.data?.[0]?.id; if (!projectId || !item.latestVersion) return show("Create or select a project before installing an agent.", "error"); const approvals = item.latestVersion.permissions.filter(value => dangerous.has(value)); if (approvals.length && !window.confirm(`Approve these dangerous permissions for this project?\n\n${approvals.join("\n")}`)) return; try { await marketplaceApi.installAgent(projectId, item.id, item.latestVersion.id, approvals); show(`Installed ${item.title} in ${projects.data?.[0]?.name}.`); } catch (error) { show(error instanceof Error ? error.message : "Installation failed.", "error"); } };
  return <main className="dashboard-content feature-page marketplace-page"><header className="feature-heading"><div><p className="dashboard-date">EXTEND YOUR WORKSPACE</p><h1>Marketplace</h1><p>Versioned packages with validated manifests and explicit project permissions.</p></div><button className="create-button" onClick={() => setPublishOpen(true)}>+ Publish package</button></header>
    <section className="marketplace-toolbar"><input aria-label="Search marketplace" placeholder="Search packages, authors, and capabilities…" value={search} onChange={event => setSearch(event.target.value)} /><div>{categories.map(option => <button key={option.label} className={category === option.value ? "active" : ""} onClick={() => setCategory(option.value)}>{option.label}</button>)}</div></section>
    {loading ? <p className="marketplace-state">Loading verified packages…</p> : items.length === 0 ? <p className="marketplace-state">No published packages match this filter.</p> : <section className="marketplace-grid">{items.map(item => <article className="marketplace-card" key={item.id}><div className="marketplace-card-top"><span>{item.category}</span><b>v{item.latestVersion?.version ?? "draft"}</b></div><h2>{item.title}</h2><p>{item.description}</p><div className="marketplace-tags">{item.tags.map(tag => <small key={tag}>{tag}</small>)}</div><footer><span>by @{item.author.userName} · ↓ {item.downloads} · ♥ {item.likes}</span><div><button onClick={async () => update(await marketplaceApi.like(item.id, !item.isLiked))}>{item.isLiked ? "Unlike" : "Like"}</button><button onClick={async () => update(await marketplaceApi.save(item.id, !item.isSaved))}>{item.isSaved ? "Saved" : "Save"}</button>{item.category === "AiAgent" ? <button className="primary" onClick={() => void install(item)}>Install</button> : <button disabled title="A sandboxed runtime for this category is not enabled yet.">Catalog only</button>}</div></footer></article>)}</section>}
    {publishOpen && <PublishDialog close={() => setPublishOpen(false)} saved={() => { setPublishOpen(false); void load(); }} />}</main>;
}

function PublishDialog({ close, saved }: { close: () => void; saved: () => void }) {
  const [form, setForm] = useState({ title: "", description: "", category: "AiAgent" as MarketplaceCategory, tags: "", version: "1.0.0", permissions: "project.read", manifest: '{\n  "name": "Project reviewer",\n  "systemPrompt": "Review project files safely.",\n  "allowedTools": []\n}' }); const [busy, setBusy] = useState(false); const { show } = useToast();
  const payload = useMemo<CreateMarketplaceInput | null>(() => { try { return { title: form.title, description: form.description, category: form.category, tags: form.tags.split(",").map(x => x.trim()).filter(Boolean), version: form.version, permissions: form.permissions.split(",").map(x => x.trim()).filter(Boolean), manifest: JSON.parse(form.manifest) }; } catch { return null; } }, [form]);
  const submit = async () => { if (!payload) return show("Manifest must be valid JSON.", "error"); setBusy(true); try { const created = await marketplaceApi.create(payload); const version = created.versions[0]; if (version) await marketplaceApi.publish(created.item.id, version.id); show("Package validated and published."); saved(); } catch (error) { show(error instanceof Error ? error.message : "Publish failed.", "error"); } finally { setBusy(false); } };
  return <div className="dialog-backdrop"><section className="dialog marketplace-dialog"><header><h2>Publish a versioned package</h2><button onClick={close}>×</button></header><label>Title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><div className="marketplace-form-row"><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value as MarketplaceCategory })}>{categories.slice(1).map(x => <option key={x.label} value={x.value}>{x.label}</option>)}</select></label><label>Version<input value={form.version} onChange={e => setForm({ ...form, version: e.target.value })} /></label></div><label>Tags (comma separated)<input value={form.tags} onChange={e => setForm({ ...form, tags: e.target.value })} /></label><label>Permissions (comma separated)<input value={form.permissions} onChange={e => setForm({ ...form, permissions: e.target.value })} /></label><label>Manifest JSON<textarea className="manifest-editor" value={form.manifest} onChange={e => setForm({ ...form, manifest: e.target.value })} /></label><p className="permission-note">Dangerous permissions require separate approval during project installation. Executable frontend scripts and secrets are rejected.</p><footer><button onClick={close}>Cancel</button><button className="ui-button primary" disabled={busy} onClick={() => void submit()}>{busy ? "Validating…" : "Validate & publish"}</button></footer></section></div>;
}
