import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState";
import { moderationApi, type ContentReport, type ModerationAction, type ReportState, type ReportTargetType } from "../features/moderation/api";
import { useToast } from "../contexts/ToastContext";
import "./ModerationPage.css";

const states: Array<ReportState | ""> = ["", "Pending", "Reviewing", "ActionTaken", "Dismissed"];
const targets: Array<ReportTargetType | ""> = ["", "Post", "Comment", "Project", "Snippet", "Profile"];

export function ModerationPage() {
  const [state, setState] = useState<ReportState | "">("Pending"); const [target, setTarget] = useState<ReportTargetType | "">(""); const [page, setPage] = useState(1); const client = useQueryClient(); const { show } = useToast();
  const queue = useQuery({ queryKey: ["moderation", state, target, page], queryFn: () => moderationApi.queue(state || undefined, target || undefined, page) });
  const action = useMutation({ mutationFn: ({ report, value }: { report: ContentReport; value: ModerationAction }) => { const note = window.prompt("Required moderation note")?.trim(); if (!note) throw new Error("A moderation note is required."); return moderationApi.act(report.id, value, note); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ["moderation"] }); show("Moderation action recorded."); }, onError: error => show(error.message, "error") });
  return <main className="moderation-page"><header><div><small>TRUST & SAFETY</small><h1>Content moderation</h1><p>Every state change and enforcement action is immutable and audit logged.</p></div><b>{queue.data?.total ?? 0} reports</b></header><nav><select value={state} onChange={e => { setState(e.target.value as ReportState | ""); setPage(1); }}>{states.map(x => <option value={x} key={x || "all"}>{x || "All states"}</option>)}</select><select value={target} onChange={e => { setTarget(e.target.value as ReportTargetType | ""); setPage(1); }}>{targets.map(x => <option value={x} key={x || "all"}>{x || "All targets"}</option>)}</select></nav>{queue.isLoading ? <LoadingState /> : queue.isError ? <ErrorState message={queue.error.message} retry={() => queue.refetch()} /> : !queue.data?.items.length ? <EmptyState title="Queue is clear" description="No reports match the selected filters." /> : <section className="moderation-list">{queue.data.items.map(report => <article key={report.id}><header><span className={`moderation-state ${report.state.toLowerCase()}`}>{report.state}</span><b>{report.targetType}</b><small>{new Date(report.createdAt).toLocaleString()}</small></header><h2>{report.targetLabel || "Removed content"}</h2><p><strong>{report.reason}</strong>{report.details ? ` — ${report.details}` : ""}</p><small>Reported by @{report.reporter.userName}{report.assignedModerator ? ` · assigned to @${report.assignedModerator.userName}` : ""}</small>{report.actions.length > 0 && <details><summary>Audit trail ({report.actions.length})</summary>{report.actions.map(item => <div key={item.id}><b>{item.action}</b><span>{item.previousState} → {item.newState}</span><p>{item.note}</p><small>@{item.moderator.userName} · {new Date(item.createdAt).toLocaleString()}</small></div>)}</details>}<footer>{report.state === "Pending" && <button onClick={() => action.mutate({ report, value: "StartReview" })}>Start review</button>}{report.state === "Reviewing" && <><button onClick={() => action.mutate({ report, value: "Dismiss" })}>Dismiss</button><button onClick={() => action.mutate({ report, value: "RestoreToPending" })}>Return to queue</button>{report.targetType === "Profile" ? <button className="danger" onClick={() => action.mutate({ report, value: "SuspendProfile" })}>Suspend profile</button> : <button className="danger" onClick={() => action.mutate({ report, value: "RemoveContent" })}>Remove content</button>}</>}</footer></article>)}</section>} {queue.data && <footer className="moderation-pages"><button disabled={page === 1} onClick={() => setPage(x => x - 1)}>Previous</button><span>Page {page}</span><button disabled={page * queue.data.pageSize >= queue.data.total} onClick={() => setPage(x => x + 1)}>Next</button></footer>}</main>;
}
