import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ErrorState, LoadingState } from "../components/AsyncState";
import { settingsApi, type Preference } from "../features/settings/api";
import { useToast } from "../contexts/ToastContext";
import { languages, type Language, type TranslationKey } from "../contexts/LanguageContext";
import { useLanguage } from "../hooks/useLanguage";
import { useTheme } from "../hooks/useTheme";
import type { ThemePreference } from "../contexts/ThemeContext";
import { useAuth } from "../hooks/useAuth";
import { useNavigate, useSearchParams } from "react-router-dom";
import { usePageTranslation } from "../hooks/usePageTranslation";

const profileSchema=z.object({firstName:z.string().min(1).max(80),lastName:z.string().min(1).max(80),bio:z.string().max(500).optional()});
const passwordSchema=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(10).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/).regex(/[^a-zA-Z0-9]/),confirmPassword:z.string(),revokeOtherSessions:z.boolean()}).refine(x=>x.newPassword===x.confirmPassword,{path:["confirmPassword"],message:"Passwords do not match."});
type ProfileForm=z.infer<typeof profileSchema>;type PasswordForm=z.infer<typeof passwordSchema>;
export function SettingsPage(){
 const {session,logout}=useAuth(); const isDemo=Boolean(session?.user.isDemo); const [searchParams]=useSearchParams(); const [section,setSection]=useState("profile"),[loggingOut,setLoggingOut]=useState(false),qc=useQueryClient(),{show}=useToast(),settings=useQuery({queryKey:["settings",session?.user.id],queryFn:settingsApi.get,refetchOnMount:"always"}),sessions=useQuery({queryKey:["settings","sessions",session?.user.id],queryFn:settingsApi.sessions,enabled:section==="security"&&!isDemo}); const {setLanguage,t}=useLanguage(); const {preference:themePreference,setThemePreference}=useTheme(); const navigate=useNavigate(); const {pt}=usePageTranslation();
 useEffect(()=>{const value=settings.data?.preferences.language;if(languages.some(item=>item.code===value))setLanguage(value as Language)},[settings.data?.preferences.language,setLanguage]);
 useEffect(()=>{const value=settings.data?.preferences.theme;if(value==="system"||value==="light"||value==="dark")setThemePreference(value)},[settings.data?.preferences.theme,setThemePreference]);
 useEffect(()=>{const requested=searchParams.get("section");if(requested==="profile")setSection("profile")},[searchParams]);
 const profile=useForm<ProfileForm>({resolver:zodResolver(profileSchema),values:settings.data?{firstName:settings.data.profile.firstName,lastName:settings.data.profile.lastName,bio:settings.data.profile.bio??""}:undefined});
 const password=useForm<PasswordForm>({resolver:zodResolver(passwordSchema),defaultValues:{currentPassword:"",newPassword:"",confirmPassword:"",revokeOtherSessions:true}});
 const saveProfile=useMutation({mutationFn:settingsApi.profile,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Profile updated.")},onError:e=>show(e.message,"error")});
 const savePassword=useMutation({mutationFn:(v:PasswordForm)=>settingsApi.password(v),onSuccess:()=>{password.reset();show("Password changed.")},onError:e=>show(e.message,"error")});
 const savePrefs=useMutation({mutationFn:settingsApi.preferences,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Preferences saved.")}});
 const saveNotifications=useMutation({mutationFn:settingsApi.notifications,onSuccess:()=>show("Notification preferences saved.")});
 const avatar=useMutation({mutationFn:settingsApi.avatar,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Avatar updated.")},onError:e=>show(e.message,"error")});
 const revoke=useMutation({mutationFn:settingsApi.revoke,onSuccess:()=>{void sessions.refetch();show("Session revoked.")}});
 if(settings.isLoading)return <main className="settings-page"><LoadingState label={t("loadingSettings")}/></main>;if(settings.isError)return <main className="settings-page"><ErrorState message={settings.error.message} retry={()=>settings.refetch()}/></main>;const data=settings.data!;
 const updatePreference=(key:keyof Preference,value:string|boolean)=>{if(key==="language")setLanguage(value as Language);if(key==="theme")setThemePreference(value as ThemePreference);savePrefs.mutate({...data.preferences,[key]:value})};
 const signOut=async()=>{if(loggingOut)return;setLoggingOut(true);try{await logout();show(pt("signedOut"));navigate("/login",{replace:true})}catch(error){show(error instanceof Error?error.message:"Logout failed.","error")}finally{setLoggingOut(false)}};
 const publicId=data.profile.publicId?.trim();
 const copyUserId=async()=>{if(!publicId){show("Your Public ID is unavailable. Refresh the page and try again.","error");return}try{await navigator.clipboard.writeText(publicId);show("Public ID copied. Share it to start a direct chat.")}catch{show("Unable to copy the Public ID.","error")}};
 return <main className="settings-page"><header><p>{t("accountCenter")}</p><h1>{t("settings")}</h1><span>{t("settingsIntro")}</span></header><div className="settings-console"><nav>{([["profile","profile"],["appearance","appearance"],["notifications","notifications"],["security","security"]] as Array<[string,TranslationKey]>).map(([id,label])=><button className={section===id?"active":""} onClick={()=>setSection(id)} key={id}>{t(label)}</button>)}<button className={`logout-nav ${section==="logout"?"active":""}`} onClick={()=>setSection("logout")}>{pt("logout")}</button></nav><section className="settings-content">
 {section==="profile"&&<><div className="settings-section-heading"><div><h2>{t("profileInfo")}</h2><p>{t("profileCopy")}</p></div><label className="avatar-upload">{data.profile.avatarUrl?<img src={data.profile.avatarUrl}/>:<span>{data.profile.firstName[0]}</span>}<input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>e.target.files?.[0]&&avatar.mutate(e.target.files[0])}/><small>{t("changeAvatar")}</small></label></div><div className="share-user-id"><div><span>YOUR CHAT ID</span><code>{publicId?`@${publicId}`:"Unavailable"}</code><small>Share this short Public ID with another NexaCode user so they can start a direct conversation.</small></div><button type="button" disabled={!publicId} onClick={()=>void copyUserId()}>Copy ID</button></div><form className="settings-form" onSubmit={profile.handleSubmit(v=>saveProfile.mutate(v))}><div className="form-row"><label>{t("firstName")}<input {...profile.register("firstName")}/><small>{profile.formState.errors.firstName?.message}</small></label><label>{t("lastName")}<input {...profile.register("lastName")}/></label></div><label>{t("username")}<input value={data.profile.userName} disabled/></label><label>{t("email")}<input value={data.profile.email} disabled/></label><label>{t("biography")}<textarea rows={5} {...profile.register("bio")}/><small>{profile.formState.errors.bio?.message}</small></label><button className="ui-button primary">{t("saveProfile")}</button></form></>}
 {section==="appearance"&&<><SettingsTitle title={t("appearanceLanguage")} copy={t("appearanceCopy")}/><div className="settings-options"><label><span><b>{t("themeLabel")}</b><small>{t("themeCopy")}</small></span><select value={themePreference} onChange={e=>updatePreference("theme",e.target.value)}><option value="system">{t("system")}</option><option value="light">{t("light")}</option><option value="dark">{t("dark")}</option></select></label><label><span><b>{t("language")}</b><small>{t("languageCopy")}</small></span><select value={data.preferences.language} onChange={e=>updatePreference("language",e.target.value)}>{languages.map(item=><option value={item.code} key={item.code}>{item.nativeLabel} — {item.label}</option>)}</select></label>{([["compactMode","compactMode"],["reducedMotion","reducedMotion"],["securityAlertsEnabled","securityAlerts"]] as const).map(([key,label])=><label key={key}><span><b>{t(label)}</b><small>{t("savedAccount")}</small></span><input type="checkbox" checked={data.preferences[key]} onChange={e=>updatePreference(key,e.target.checked)}/></label>)}</div></>}
 {section==="notifications"&&<><SettingsTitle title={t("notificationPrefs")} copy={t("notificationCopy")}/><div className="notification-settings"><header><span>{t("event")}</span><span>{t("inApp")}</span><span>{t("email")}</span></header>{data.notifications.map((item,index)=><div key={item.type}><b>{item.type.replace(/([A-Z])/g," $1")}</b><input type="checkbox" checked={item.inAppEnabled} onChange={e=>{const next=[...data.notifications];next[index]={...item,inAppEnabled:e.target.checked};saveNotifications.mutate(next)}}/><input type="checkbox" checked={item.emailEnabled} onChange={e=>{const next=[...data.notifications];next[index]={...item,emailEnabled:e.target.checked};saveNotifications.mutate(next)}}/></div>)}</div></>}
 {section==="security"&&<><SettingsTitle title={t("passwordSessions")} copy={t("passwordCopy")}/>{isDemo?<div className="demo-locked-panel"><span>◆</span><div><strong>Security settings are locked in Demo Mode</strong><p>Demo personas do not expose passwords. Sessions are short-lived and all demo data resets automatically.</p></div></div>:<><form className="settings-form password-form" onSubmit={password.handleSubmit(v=>savePassword.mutate(v))}><label>{t("currentPassword")}<input type="password" {...password.register("currentPassword")}/></label><div className="form-row"><label>{t("newPassword")}<input type="password" {...password.register("newPassword")}/><small>{password.formState.errors.newPassword?.message}</small></label><label>{t("confirmPassword")}<input type="password" {...password.register("confirmPassword")}/><small>{password.formState.errors.confirmPassword?.message}</small></label></div><label className="check-row"><input type="checkbox" {...password.register("revokeOtherSessions")}/> {t("revokeOthers")}</label><button className="ui-button primary">{t("changePassword")}</button></form><div className="session-list"><h3>{t("activeSessions")}</h3>{sessions.isLoading?<LoadingState label={t("activeSessions")}/>:sessions.data?.map(item=><article key={item.id}><span>◉</span><div><b>{item.device}</b><small>{item.ipAddress??t("unknownIp")} · {new Date(item.lastSeenAt).toLocaleString()}</small></div><button disabled={item.isCurrent} onClick={()=>revoke.mutate(item.id)}>{item.isCurrent?t("currentSession"):t("revoke")}</button></article>)}</div></>}</>}
 {section==="logout"&&<><SettingsTitle title={pt("logoutTitle")} copy={pt("logoutCopy")}/><div className="logout-settings-card"><span aria-hidden="true">↪</span><div><strong>{userDisplayName(data.profile.firstName,data.profile.lastName)}</strong><small>{data.profile.email}</small></div><button disabled={loggingOut} onClick={()=>void signOut()}>{loggingOut?`${pt("logout")}…`:pt("logout")}</button></div></>}
 </section></div></main>
}
function SettingsTitle({title,copy}:{title:string;copy:string}){return <div className="settings-section-heading"><div><h2>{title}</h2><p>{copy}</p></div></div>}
function userDisplayName(firstName:string,lastName:string){return `${firstName} ${lastName}`.trim()}
